### ISSUE TITLE
To Fix

### ISSUE THREAD

**Issue by nfeliciano** [nfeliciano/githubpaper#10]
Here I list all the issues I saw on my pass today. For most of them, I put my suggested fixes afterwards. I'll check them as I actually fix them.

**Section 1**:
- [x] _Such insights can be used by future instructors who may struggle to decide if they should use GitHub in their courses, or if they decide to use it, how they should use GitHub in an educational context_
  Noel: A little awkward `@alexey: it is not super bad, but perhaps we can just remove "if they decide to use it,"`

**2.1**:
- [x] ...Web 2.0 and ‘the social Web’, LMS have become... -> _LMSes_
- [x] ...have expressed concerns regarding their readiness to incorporate and emphasize student participation... -> _...regarding the readiness of traditional LMSes to incorporate..._ `@cassie please advise`
- [x] ...more focused on administration rather than the learner... -> _...rather than on the learner..._ `@cassie please advise`

**2.3**:
- [x] The authors discussed that learning how to do pull requests is an essential industry skill... -> _The authors described the ability to do pull requests as an essential industry skill..._ `@cassie please advise`
- [x] ...allowed the instructors to encourage student participation through its transparency features... -> _...allowed them to encourage..._
- [x] ...to simplify assignments and submissions, however, they felt that... -> _to simplify assignments and submissions. However, they felt that..._ `@alexey: I think previous phrasing was better in this case`

**3**:
- [x] When adopting a new tool for a course, particularly a tool not tailored towards education, there may be some friction involved or a variety of other challenges. -> _When adopting a new tool for a course---particularly a tool not tailored towards education---there may be some friction..._ `@cassie please advise`

**3.1**:
- [x] ...in the DS course, building systems that involve multiple computational devices, and in the SE course, evolving existing systems or utilizing them to create new ones. -> _building systems that involve multiple computational devices in the DS course, and evolving existing systems or utilizing them to create new ones in the SE course._  
  A little awkward `@alexey: perhaps, but this describes the courses, and I can't help with this`

**3.2**:
- [x] ...project hosting through various repositories... -> _project hosting in student repositories_ `@alexey: I would say "through student repositories"` `@nfeli: fixed`
- [x] ...cases other instructors described in [33]... -> _cases other instructors described in our previous study [33]_ `@alexey: I think it was changed to not say "our previous study", so reverse this change`
- [x] ...this possibility was not emphasized to the students during the courses. -> _...the instructor did not emphasize this feature during the courses_ `@alexey: I like the previous phrasing - I would reverse` `@nfeli: fixed`
- [x] The other main use case... -> _The other main use of GitHub..._
- [x] Using the repository’s ‘issues’ page... -> _Using each course repository's 'issues' page..._ `@alexey: I know the change makes it more specific, but I think previous phrasing was clearer. I would reverse`
- [x] would ‘@mention’ their group members -> Italicize '@mention'
- [x] Moodle was used for work that... -> _Moodle was used for artifacts that..._
- [x] Participation was voluntary and students who signed up were not required to participate in all phases of the study—those who were interviewed did not necessarily respond to the subsequent validation survey (discussed below).  
  A little awkward `@alexey: it's fine, leave it this way` `@nfeli: left alone`

**3.5**:
- [x] ...our research design that we mention here. -> _...our research design that we describe here._

**4.1**:
- [x] Investigating the student perspective, our study reveals emerging themes on the student perceptions on the beneﬁts of using GitHub in education. -> _Our study reveals emerging themes pertaining to the benefits of using GitHub in education from the student perspective._ `@cassie please advise`
- [x] ...look at the work of other students, many reported... -> _...many students reported_
- [x] ...students utilized code taken from other groups... -> _...students utilized code that other groups built..._
- [x] While our participants didn’t contribute in this way, they saw how... -> _While this was not utilized in these courses, students saw how..._ `@alexey: I like the previous phrasing better.` `@nfeli: the issue with the previous phrasing was that the quote refers to something the instructor can do (seeing all the student's mistakes) rather than a way students can contribute`

**4.2**:
- [x] Challenge: The Perils of Public Projects  
  Not sure I like this title `@alexey: I would leave it` `@nfeli: left alone`
- [x] While on the other hand -> _On the other hand..._ `@alexey: because the previous sentence uses "on the one hand" I would leave "while"`
- [x] ...there may be workarounds for many of the tasks needed, GitHub certainly struggles to meet some basic educational needs... -> _...there may be workarounds for many of the tasks GitHub needs to fulfil, it struggles to meet some basic educational needs..._ `@alexeyza: I prefer previous phrasing, to me it is clearer` `@nfeli: left alone`
- [x] ...which some students felt would be discouraging the use of this feature... -> _...which some students felt would discourage them from using this feature..._

**4.3**:
- [x] For example, promoting the use of Pull Requests as a way to suggest corrections to course materials, or encouraging student-to-student feedback and contributions  
  Seems awkward `@alexey: seems fine, leave it` `@nfeli: left alone`
- [x] ...but it is up to the instructor to consider which features the instructor would like to use and how... -> _...which features they would like to use and how..._
- [x] ...to simplify contribution process... -> _...to simplify the contribution process..._

**5**:
- [x] Few of GitHub’s transparency features were mentioned by the students— while others, features like the News Feed or graphs, were not discussed in the context of group projects -> _Few of GitHub's transparency features, such as News Feeds or Graphs, were mentioned by the students in the context of group projects._ `@alexey: I like the previous phrasing for some reason` `@nfeli: OH I just understood what we were saying with the first. It makes sense, reverting`
- [x] Students also acknowledged the importance of seeing a history of work -> _However, students acknowledged..._ `@alexey: reverse change. It was OK, because the first sentence in that paragraph was related to this and both were positive, so no need for "however"` `@nfeli: fixed`

**Comment by nfeliciano** [comment]
Let me know if you disagree with any of the changes, or just change/revert them

**Comment by alexeyza** [comment]
I don't like LMSes (I don't remember if we used it in the paper)

**Comment by nfeliciano** [comment]
It's how we've been doing it in the paper, and if I remember correctly, Cassie said we just have to make a choice. We can change all instances of LMSes to LMS.

**Comment by alexeyza** [comment]
If we already used LMSes then fine...

I'll go over this later on, I can't today - but it's good to have a list that documents everything in one place.

**Comment by nfeliciano** [comment]
Okay no problem. I have a few other changes to make later today and I'll list them. Mainly the ones already here that I haven't checked off yet though.

**Comment by nfeliciano** [comment]
Reverted some, left some that you wanted to revert that I still want to think about, and a comment on the last one in 4.1

**Comment by cpetrachenko** [comment]
Wikipedia uses LMSs...some LMS vendors use LMSes.

**Comment by alexeyza** [comment]
@nfeliciano can you check and let me know if there are unclosed issues/comments left?
I want to try to submit this tomorrow morning (and if needed you can resubmit until Feb 13).

**Comment by nfeliciano** [comment]
On it tonight

**Comment by nfeliciano** [comment]
Okay, I think the 4 left from this issue that we are unsure about are:

3.1: I changed this structure just to flow better. Think it works out.

3.2: "using each course repository's 'issues' page" - we disagree on this one, though it's a pretty minor point.

4.1: "Investigating the student perspective..." -> _"Our study reveals.."_ - I changed this one pretty heavily, I'm not sure about 'pertaining to' though.

4.1: "While this was not utilized in these courses, students saw how.." - We need to settle this one.

**Comment by alexeyza** [comment]
3.1 - like I said - up to you
3.2 - I guess it works. let's leave it.
4.1 - I'll ask Cassie about this one
4.1 - I'm OK with your change, but the following should be slightly improved

> While **this feature** was not utilized in these courses, students saw how **the feature** provides one with the ability to examine the final product, as well as the process used to get there.

Perhaps change the second appearance to "it"?

**Comment by nfeliciano** [comment]
Agree on the second 4.1. Changing it now

**Comment by nfeliciano** [comment]
The Discussion heading has been fixed automatically too

**Comment by alexeyza** [comment]
So, can I try to submit it? 
(there are some preparations that need to be done, and also, there is a tool to check our paper prior to submission - so it may complain)

**Comment by nfeliciano** [comment]
Oops, one more commit in a minute. Forgot something in #9

**Comment by nfeliciano** [comment]
Okay, should be good for submission

**Comment by alexeyza** [comment]
Cassie hasn't finished with her pass, I'll wait and update you when I've submitted.
