### ISSUE TITLE
There is still some inconsistency in capitalization

### ISSUE THREAD

**Issue by cpetrachenko** [nfeliciano/githubpaper#11]
For example, Pull Request vs pull request

**Comment by nfeliciano** [comment]
Fixed, made them all lower case. My only question, @cpetrachenko, is if it should be smaller case when we introduce the initialism? I assume yes, but just to make sure.

Chapter 4, 'Encouraging Student Contributions to Course Content'    

> One of the benefits that GitHub offers over traditional Learning Management Systems is the ability for students to suggest corrections and make changes to course materials via pull requests (PRs).

**Comment by alexeyza** [comment]
I think the first appearance of "... via pull requests (PRs)" is fine as it conforms with rest of our style (all lower case for "pull requests" and upper case for "PR")

**Comment by cpetrachenko** [comment]
I think the Pull Request with caps is a result of using caps with feature names. You might want to run through and make sure that all other feature names are then also lower case.

**Comment by cpetrachenko** [comment]
I think that technically a spelled out form of an initialism or acronym needs caps, but whatev...
