### ISSUE TITLE
References

### ISSUE THREAD

**Issue by nfeliciano** [nfeliciano/githubpaper#2]
Still missing a couple. Track them.

**Comment by nfeliciano** [comment]
I didn't catch this in the PR #4 but the citations are missing, despite the references being there and seemingly correct. Any ideas @alexeyza ?

**Comment by alexeyza** [comment]
yes, the missing references are not in the bib file.

**Comment by alexeyza** [comment]
at least not that I could find

**Comment by nfeliciano** [comment]
Oh right, sorry; I noticed a lot references that show up as [?] that I think are in the bib file and thought it was all of them, it's only a couple. I'll fix this right now
