### ISSUE TITLE
RQs

### ISSUE THREAD

**Issue by cpetrachenko** [nfeliciano/githubpaper#5]
I don't know why I've ignored this for so long, but if possible, you should rephrase your RQs.

RQ1: How do students benefit from using GitHub in their courses?
RQ2: What challenges do students face when using GitHub in their courses?
RQ3: What recommendations do students have for instructors wishing to use GitHub in a course?

But I know you're now on your third publication related to this work and it's likely too late to do anything. But I wanted to go on record regardless. :)

**Comment by nfeliciano** [comment]
Rephrase in what way, @cpetrachenko ?

**Comment by cpetrachenko** [comment]
My edits are noted above.

Peggy also changed these in the intro to:
What are student perceptions on the benefits of using GitHub for their software engineering courses?
What challenges do students face when GitHub is used by software engineering course instructors?
What recommendations can we give to software engineering instructors who wish to use GitHub for teaching?

Ask @margaretstorey which ones she prefers.

**Comment by cpetrachenko** [comment]
I tweaked RQ3 again in the Methodology...
RQ3: What recommendations can we provide software engineering instructors who wish to use GitHub for teaching?

**Comment by alexeyza** [comment]
Is this relevant? Can we close this issue?
