### ISSUE TITLE
Instructor vs professor

### ISSUE THREAD

**Issue by cpetrachenko** [nfeliciano/githubpaper#7]
This has been bugging me...

In the top half of the methodology section, we talk about the instructor using github to do X and Y. In the Research Methods subsection, we mention that we interviewed all instructors...prof and lab instructors.

So, when we talk about "the instructor using github to do X and Y", do we really mean the prof? And if so, should we just say that?

**Comment by nfeliciano** [comment]
Will not address for the moment, this is also somewhat mitigated by the fact that we remove mentions of the lab instructors
