### ISSUE TITLE
SoftEng (SE) and CompSci (CS) courses vs DistSystems (DS) and SoftEvol (SE) courses

### ISSUE THREAD

**Issue by cpetrachenko** [nfeliciano/githubpaper#8]
In the methodology, we talk about Distributed Systems (DS) and Software Evolution (SE) courses. At the top of the 4-github.tex file, we talk about Computer Science (CS) and Software Engineering (SE) courses. I think you should stick with the former...I'll work to remove the later from the 4-github.tex file, but you should also do this elsewhere.

**Comment by nfeliciano** [comment]
Oh, we're not using the 4-github.tex file anymore

**Comment by nfeliciano** [comment]
I should've probably deleted it, but everything in that file is now in the methodology section. Sorry!

**Comment by cpetrachenko** [comment]
then I'll stop looking at it
