### ISSUE TITLE
Camera ready plan

### ISSUE THREAD

**Issue by alexeyza** [nfeliciano/githubpaper#9]
Items to do for final submission (by _February 13th_):
- [x] Fix the typo mentioned by reviewer (Importnat -> important)
- [x] Page 8, discussion subheading should be in the next column
- [x] Footnote 3 in page 5 (cnet footnote) goes off the page
- [x] There are still instances of CS being used to quote students (instead of DS) in 4.2 and later
- [x] Follow submission guidelines (sent to us by email) to prepare the paper (i.e., add copyright disclaimer to the paper)
- [x] See https://github.com/nfeliciano/githubpaper/issues/11  Do you care?
- [x] Read the whole paper again and look for things that need improvement
- [x] Run the paper by Cassie
- [x] Alexey needs to register to ICSE
- [x] submit paper on time :)

**Comment by alexeyza** [comment]
Paper ID: **ICSE16-SEET-042**

Author kit (submission guidelines):
http://conferences.computer.org/icse/AuthorKit/Companion/AuthorKit.html

**Comment by nfeliciano** [comment]
\CopyrightYear{2016} 
\setcopyright{acmcopyright}
\conferenceinfo{ICSE '16 Companion,}{May       14-22, 2016, Austin, TX, USA}

              \isbn{978-1-4503-4205-6/16/05}\acmPrice{\$15.00}
\doi{http://dx.doi.org/10.1145/2889160.2889195}

**Comment by alexeyza** [comment]
I hate that the Introduction title is on a separate page. We should try to fix it.
